FROM node:14 as build-stage

RUN apt-get update && apt-get install -y git
RUN git clone https://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@github.com/hypersign-protocol/studio-frontend.git /app

WORKDIR /app

RUN git checkout new-studio-server-integration

RUN npm install

# Build the Vue.js app for production
ARG VUE_APP_TITLE
ENV VUE_APP_TITLE=${VUE_APP_TITLE}

ARG VUE_APP_DESC
ENV VUE_APP_DESC=${VUE_APP_DESC}

ARG VUE_APP_VERSION
ENV VUE_APP_VERSION=${VUE_APP_VERSION}

ARG VUE_APP_STUDIO_SERVER_BASE_URL
ENV VUE_APP_STUDIO_SERVER_BASE_URL=${VUE_APP_STUDIO_SERVER_BASE_URL}

ARG VUE_APP_STUDIO_SERVER_BASE_WS
ENV VUE_APP_STUDIO_SERVER_BASE_WS=${VUE_APP_STUDIO_SERVER_BASE_WS}

ARG VUE_APP_NODE_SERVER_BASE_URL
ENV VUE_APP_NODE_SERVER_BASE_URL=${VUE_APP_NODE_SERVER_BASE_URL}

ARG VUE_APP_NODE_SERVER_BASE_URL_REST
ENV VUE_APP_NODE_SERVER_BASE_URL_REST=${VUE_APP_NODE_SERVER_BASE_URL_REST}

ARG VUE_APP_SCHEMA_GET_EP_REST
ENV VUE_APP_SCHEMA_GET_EP_REST=${VUE_APP_SCHEMA_GET_EP_REST}

ARG VUE_APP_ACCPCT_CRED_EP
ENV VUE_APP_ACCPCT_CRED_EP=${VUE_APP_ACCPCT_CRED_EP}

ARG VUE_APP_EXPLORER_BASE_URL
ENV VUE_APP_EXPLORER_BASE_URL=${VUE_APP_EXPLORER_BASE_URL}

ARG VUE_APP_STUDIO_SERVER_SAVE_SCHEMA
ENV VUE_APP_STUDIO_SERVER_SAVE_SCHEMA=${VUE_APP_STUDIO_SERVER_SAVE_SCHEMA}

ARG VUE_APP_SCHEMA_LIST_EP
ENV VUE_APP_SCHEMA_LIST_EP=${VUE_APP_SCHEMA_LIST_EP}

ARG VUE_APP_STUDIO_SERVER_CRED_LIST_EP
ENV VUE_APP_STUDIO_SERVER_CRED_LIST_EP=${VUE_APP_STUDIO_SERVER_CRED_LIST_EP}

ARG VUE_APP_STUDIO_SERVER_CRED_ISSUE_EP
ENV VUE_APP_STUDIO_SERVER_CRED_ISSUE_EP=${VUE_APP_STUDIO_SERVER_CRED_ISSUE_EP}

ARG VUE_APP_WEB_WALLET_ADDRESS
ENV VUE_APP_WEB_WALLET_ADDRESS=${VUE_APP_WEB_WALLET_ADDRESS}

ARG VUE_APP_PRESENTATION_TEMPLATE_EP
ENV VUE_APP_PRESENTATION_TEMPLATE_EP=${VUE_APP_PRESENTATION_TEMPLATE_EP}

ARG VUE_APP_SSE
ENV VUE_APP_SSE=${VUE_APP_SSE}

RUN npm run build


FROM nginx:latest as production-stage
COPY nginx.conf /etc/nginx/nginx.conf

COPY --from=build-stage /app/dist /usr/share/nginx/html

EXPOSE 80

