name: Hypersign CLI Release Workflow

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]-rc.[0-9]+"

permissions:
  contents: write
  packages: write

jobs:
  release-binaries-github:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
            node-version: 18

      - name: Install OClif
        run: yarn global add oclif
    
      - name: Build Executable (Ubuntu)
        run: oclif pack deb
        if: matrix.os == 'ubuntu-latest'

      - name: Build Executable (MacOS)
        run: oclif pack macos
        if: matrix.os == 'macos-latest'

      - name: Check if binaries are present in dist dir
        run: ls ./dist

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: false
          generate_release_notes: true
          files: |
            ./dist/**.deb
            ./dist/**.pkg

